# Generated by Django 3.2.4 on 2021-07-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='files',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='questions',
            name='reading_time',
            field=models.IntegerField(null=True),
        ),
    ]
