# Generated by Django 3.2.4 on 2021-07-01 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210701_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='files',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='reading_time',
        ),
    ]
