# Generated by Django 3.2.4 on 2021-09-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='text',
            new_name='quiz_text',
        ),
        migrations.AlterField(
            model_name='result',
            name='result',
            field=models.FloatField(default=0.0),
        ),
    ]
