# Generated by Django 3.2.4 on 2021-09-04 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210904_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='text',
            new_name='answer_text',
        ),
    ]
